#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define EEPROM_SETTINGS_ADDR 0x0000
#define EEPROM_SETTINGS_LEN 0x0040

#define SERIAL_PORT Serial
#define SERIAL_PORT_SPEED 38400
#define SERIAL_RX_PIN 0
#define RTC_POWER_PIN 4
#define LED_SYNC LED_BUILTIN
#define SYNC_WATCHDOG_TIMEOUT 1000

#define COMMAND_BUFFER_SIZE 128
#define RESPONSE_BUFFER_SIZE 128
#define CMDRSP_BUFF_TYPE uint8_t

#define DEBUG_SERIAL_PORT SERIAL_PORT

#endif
